package at.qe.skeleton.ui.controllers;

import at.qe.skeleton.model.AccessPoint;
import at.qe.skeleton.services.AccessPointService;
import lombok.Getter;
import lombok.Setter;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;

import java.io.Serializable;
import java.util.Collection;

@Getter
@Setter
@Controller
public class AccessPointController implements Serializable {

    @Autowired
    private AccessPointService accessPointService;

    private AccessPoint accessPoint;
    private AccessPoint accessPointToBeCreated = new AccessPoint();
    private String location;

    /**
     * Returns a list of all access points.
     * @return
     */
    public Collection<AccessPoint> getAccessPoints(){
        return accessPointService.getAllAccessPoint();
    }

    /**
     * Create a new access point. Only location is needed since ID is autogenerated and validated is always set to false.
     */
    public void doCreateAccessPoint(){
        this.accessPointService.createAccessPoint(location);
        this.accessPointToBeCreated = null;
        this.location = null;
    }

    /**
     * Deletes an accesspoint
     */

    public void doDeleteAccessPoint(){
         this.accessPointService.deleteAccessPoint(accessPoint);
         accessPoint = null;
    }
}

