from enum import Enum

# class syntax
class Is(Enum):
    IMPLEMENT_DATABASE = 0
    CHECK_WEBAPP_FOR_NEW_SENSORSTATION = 1
    READ_SENSOR_VALUES = 2
    CHECK_BOARDER_VALUER = 3
    WRITE_VALUES_TO_WEBAPP = 4
    CHECK_FOR_NEW_BOARDER_VALUES = 5
    CHECK_SENSOR_STATION_ALARM = 6